source:          ./docs
destination:     ./.site

collections:
  words:
    output: true
    permalink: /:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
