source:          ./docs
destination:     ./.site

collections:
  words:
    output: true
    permalink: /:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# global variables
navtitle: "kiavash.page"
sitename: "Kiavash Page"
sitedescription: "Kiavash Page: Writer of fiction, poetry, and essays."
contactemail: "contact@kiavash.page"
author: "Kiavash Page"
bio: "Writer of fiction, poetry and the occassional essay."
