source:          ./docs
destination:     ./.site

collections:
  words:
    output: true
    permalink: /:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
        path: ""
        type: "words"
    values:
        headertype: "content"

# global variables
navtitle: "kiavash.page"
sitename: "Kiavash Page"
sitedescription: "Kiavash Page: Writer of fiction, poetry, and essays."
contactemail: "contact@kiavash.page"
author: "Kiavash Page"
bio: "I write as a way of reminding myself to remain present in life — that our uncertain existence is meant to be experienced, not won or solved.
<br><br>Join my mailing list below to be updated when I publish something new!"
spotlighttitle: "Recently Published"
mailinglist-subscribe-url: "https://forms.gle/GSKxepE7EPgGcGRC9"
mailinglist-unsubscribe-url: "https://forms.gle/CNxD1Lu1kmxsQ4Ze9"

category_names:
  - "poem"
  - "story"
  - "essay"
category_paths:
    poem: "poems"
    story: "stories"
    essay: "essays"
