source:          ./docs
destination:     ./.site

collections:
  words:
    output: true
    permalink: /:categories/:name
  chapters:
    output: true
    permalink: /:categories/:path
    sort_by: number

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
        path: ""
        type: "words"
    values:
        headertype: "content"
        spotlight: false
        complete: true
        list: true
  -
    scope:
        path: ""
        type: "chapters"
    values:
        headertype: "content"
        complete: true
        list: true

# global variables
navtitle: "Kiavash Page"
sitename: "Kiavash Page"
sitedescription: "Kiavash Page: Author of fiction, poetry, and essays."
contactemail: "contact@kiavash.page"
author: "Kiavash Page"
bio: "Writing helps remind me to stay present in life. That boredom is a choice, and there's always something new to see in familiar places.
<br><br>Join the mailing list below for updates on new content!"
spotlighttitle: "Spotlight"
mailinglist-subscribe-url: "https://forms.gle/GSKxepE7EPgGcGRC9"
mailinglist-unsubscribe-url: "https://forms.gle/CNxD1Lu1kmxsQ4Ze9"

category_names:
  - "poem"
  - "story"
  - "essay"
  - "book"
category_paths:
    poem: "poems"
    story: "stories"
    essay: "essays"
    book: "books"
