source:          ./docs
destination:     ./.site

collections:
  words:
    output: true
    permalink: /:categories/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# global variables
navtitle: "kiavash.page"
sitename: "Kiavash Page"
sitedescription: "Kiavash Page: Writer of fiction, poetry, and essays."
contactemail: "contact@kiavash.page"
author: "Kiavash Page"
bio: "I write as a way of reminding myself to remain present in life — that our uncertain existence is meant to be experienced, not won or solved.
<br><br>Here's a collection of my work.
<br>I hope you enjoy!"
spotlighttitle: "Recent Highlights"
